services:
  s21gql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: s21gql
    working_dir: /app
    volumes:
      - .:/app
      - go-modules:/go/pkg/mod
    environment:
      - GO111MODULE=on
      - CGO_ENABLED=0

volumes:
  go-modules:
